/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class JFPrinicipalServidor extends javax.swing.JFrame {

//    private ArrayList<String> listaA;
    private int numClientes;
    private DefaultListModel<String> clienteON;
    private DefaultListModel<String> clienteOFF;
    ServidorPlay servico;

    /**
     * Creates new form JFPrinicipalServidor
     */
    public JFPrinicipalServidor() {
        clienteON = new DefaultListModel<>();
        clienteOFF = new DefaultListModel<>();

        initComponents();

        txtStatus.setText("OFFLINE");
        btmIniciarServico.setEnabled(true);
        btmPararServico.setEnabled(false);
        btmFechar.setEnabled(true);

    }

    private void preActions() {
        servico = new ServidorPlay(clienteON, clienteOFF, txtStatus, txtNumClientes);
        servico.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVersaoApp = new javax.swing.JTextField();
        jlbServerName = new javax.swing.JLabel();
        jcomboEscolhaServidor = new javax.swing.JComboBox();
        jlbClientes = new javax.swing.JLabel();
        btmIniciarServico = new javax.swing.JButton();
        btmPararServico = new javax.swing.JButton();
        btmFechar = new javax.swing.JButton();
        jlbTitulo = new javax.swing.JLabel();
        jlbStatus = new javax.swing.JLabel();
        jlnVersao = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jlbNumClientes = new javax.swing.JLabel();
        txtNumClientes = new javax.swing.JTextField();
        jscrolIpClientes = new javax.swing.JScrollPane();
        jlistIPClientes = new javax.swing.JList();
        jscrolIpClientes1 = new javax.swing.JScrollPane();
        jlistIPClientes1 = new javax.swing.JList();
        jlbClientes1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pandera Studios");

        txtVersaoApp.setEditable(false);
        txtVersaoApp.setText("v_1.0");

        jlbServerName.setText("Server Name: ");

        jcomboEscolhaServidor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "unesa", "Pander 1", "Pander 2", " " }));

        jlbClientes.setText("IPs dos Clientes que ja se Conectaram");

        btmIniciarServico.setText("INICIAR SERVIDOR");
        btmIniciarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmIniciarServicoActionPerformed(evt);
            }
        });

        btmPararServico.setText("PARAR SERVIDOR");
        btmPararServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmPararServicoActionPerformed(evt);
            }
        });

        btmFechar.setText("FECHAR");
        btmFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmFecharActionPerformed(evt);
            }
        });

        jlbTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbTitulo.setText("Pandera Studios Server");

        jlbStatus.setText("STATUS DO SERVIDOR:");

        jlnVersao.setText("Versão");

        txtStatus.setEditable(false);

        jlbNumClientes.setText("NUM. CLIENTES:");

        txtNumClientes.setEditable(false);

        jlistIPClientes.setModel(clienteON);
        jscrolIpClientes.setViewportView(jlistIPClientes);

        jlistIPClientes1.setModel(clienteOFF);
        jscrolIpClientes1.setViewportView(jlistIPClientes1);

        jlbClientes1.setText("IPs dos Clientes que Desconectaram");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jlbTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbClientes1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbClientes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbServerName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcomboEscolhaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jscrolIpClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jscrolIpClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jlnVersao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtVersaoApp, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btmPararServico, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btmIniciarServico, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jlbStatus)
                                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbNumClientes)
                                            .addComponent(txtNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btmFechar)
                                .addGap(28, 28, 28))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTitulo)
                    .addComponent(jlnVersao)
                    .addComponent(txtVersaoApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmIniciarServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmPararServico)
                        .addGap(20, 20, 20)
                        .addComponent(jlbStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jlbNumClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbServerName)
                            .addComponent(jcomboEscolhaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlbClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jscrolIpClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jlbClientes1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscrolIpClientes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmFechar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmIniciarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmIniciarServicoActionPerformed
        // TODO add your handling code here:        

        btmIniciarServico.setEnabled(false);
        btmPararServico.setEnabled(true);
        jcomboEscolhaServidor.setEnabled(false);
        preActions();
    }//GEN-LAST:event_btmIniciarServicoActionPerformed


    private void btmFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmFecharActionPerformed
        // TODO add your handling code here:
        int fechar = JOptionPane.showConfirmDialog(null, "Confirma Sair do Servidor?",
                "Servidor", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (fechar == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btmFecharActionPerformed

    private void btmPararServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmPararServicoActionPerformed
        int parar = JOptionPane.showConfirmDialog(null, "Confirma Parar o Servidor?",
                "Servidor", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (parar == 0) {

            servico.stop();
            servico.pararServ();
            txtStatus.setText("OFFLINE");
            btmIniciarServico.setEnabled(true);
            btmPararServico.setEnabled(false);
            jcomboEscolhaServidor.setEnabled(true);

        }

    }//GEN-LAST:event_btmPararServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFPrinicipalServidor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmFechar;
    private javax.swing.JButton btmIniciarServico;
    private javax.swing.JButton btmPararServico;
    private javax.swing.JComboBox jcomboEscolhaServidor;
    private javax.swing.JLabel jlbClientes;
    private javax.swing.JLabel jlbClientes1;
    private javax.swing.JLabel jlbNumClientes;
    private javax.swing.JLabel jlbServerName;
    private javax.swing.JLabel jlbStatus;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JList jlistIPClientes;
    private javax.swing.JList jlistIPClientes1;
    private javax.swing.JLabel jlnVersao;
    private javax.swing.JScrollPane jscrolIpClientes;
    private javax.swing.JScrollPane jscrolIpClientes1;
    private javax.swing.JTextField txtNumClientes;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtVersaoApp;
    // End of variables declaration//GEN-END:variables

}
